staticfy_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    member do
      patch 'promote_to_teacher'
      patch 'promote_to_student'
    end
  end

  resources :multi_choice_questions

  resources :tasks do
    post 'finish', on: :member
    # get 'retry_incorrect', on: :member
    post 'create_incorrect_task', on: :member
  end

  resources :tasks do
    post 'create_incorrect', on: :member
  end


  resources :courses do
    resources :tasks
  end

  resources :multi_choice_questions do
    post 'submit_answer', on: :member
  end

  resources :multi_choice_answers

  resources :numeric_questions do
    post 'submit_answer', on: :member
    get 'show_hint', on: :member
    get 'show_result', on: :member
  end

  resources :user_progresses

  get '/home', to: 'static_pages#home'

  # Health check route
  get "up" => "rails/health#show", as: :rails_health_check

  # Root path route
  root "static_pages#home"

  post '/tasks/:task_id/submit_answer', to: 'tasks#submit_answer', as: 'submit_answer'
  post 'user_courses/reduce_progress', to: 'user_courses#reduce_progress'
end

staticfy_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Staticfy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Assistant:wght@200..800&display=swap" rel="stylesheet">
  
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap" rel="stylesheet">
  
  </head>

  <body>

    <div class="flash-messages">
        <% flash.each do |type, message| %>
        <div class="custom-alert alert alert-<%= type == :error ? 'danger' : type %> alert-dismissible fade show">
            <%= message %>
            <button type="button" class="btn-close-md" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        <% end %>
    </div>

  
    <div class="container-fluid m-lg-0 m-md-0">
      <nav class="navbar navbar-expand-lg" style="border-bottom: 1px solid #004d00; width: 100%;">
        <a class="navbar-brand" href="/home" style="font-size: 30px; margin-left: 10px; margin-right: 30px">
          <img src="<%= asset_path('logo.png') %>" alt="Staticfy" style="height: 60px;">
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav me-auto gap-3">
            
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to 'Cursos', courses_path, class: 'nav-link' %>
              </li>

              <li class="nav-item">
                <% if current_user.user_progress.present? %>
                  <%= link_to 'Progreso', user_progress_path(current_user.id), class: 'nav-link' %>
                <% else %>
                  <span class="nav-link disabled">Progreso no disponible</span>
                <% end %>
              </li>
            <% end %>

          <% if user_signed_in? && current_user.role == 'teacher' %>
            <li class="nav-item dropdown" style="list-style: none;">
              <a class="nav-link dropdown-toggle" href="#" id="teacherDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dashboard

              </a>
              <ul class="dropdown-menu" aria-labelledby="teacherDropdown">
                <li><%= link_to 'Estado de los alumnos', user_progresses_path, class: 'dropdown-item' %></li>
                <li><%= link_to 'Preguntas', multi_choice_questions_path, class: 'dropdown-item' %></li>
                <li><%= link_to 'Tareas', tasks_path, class: 'dropdown-item' %></li>
              </ul>
            </li>
          <% end %>


          <li class="nav-item">
              <% if !user_signed_in? %>
                <%= link_to 'Log in', new_user_session_path, class: 'nav-link', style: 'color: #004d00; font-weight: 500;' %>
              <% else %>
                <%= button_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link', style: 'color: #004d00; font-weight: 500;'%>
              <% end %>
            </li>
          </ul>      

          <% if user_signed_in? && current_user.role == 'student' %>
            <%= button_to 'Convertirse en Profesor', promote_to_teacher_user_path(current_user.id), method: :patch, class: 'btn btn-link', style: 'color: #004d00; text-decoration: none;' %>
          <% end %>


          <% if user_signed_in? && current_user.role == 'teacher' %>
            <%= button_to 'Convertirse en Alumno', promote_to_student_user_path(current_user.id), method: :patch, class: 'btn btn-link', style: 'color: #004d00; text-decoration: none;' %>
          <% end %>
      
      </nav>
    </div>

    <div>
      <%= yield %>
    </div>

  <div>
    <% unless controller_name == 'numeric_questions' && action_name == 'show_result' || action_name == 'show_hint'%>
      <!-- Background SVG -->
      <div class="text-center" style="margin-top: 30px;">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320" style="max-width: 100%; height: auto;">
          <path fill="#28a745" fill-opacity="1" d="M0,160L48,165.3C96,171,192,181,288,160C384,139,480,85,576,74.7C672,64,768,96,864,101.3C960,107,1056,85,1152,96C1248,107,1344,149,1392,170.7L1440,192V320H1392C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320H0V160Z"></path>
        </svg>
      </div>
    <% end %>
  </div>


  </body>
</html>