staticfy_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    member do
      patch 'promote_to_teacher'
      patch 'promote_to_student'
    end
  end

  resources :multi_choice_questions

  resources :tasks do
    post 'finish', on: :member
    # get 'retry_incorrect', on: :member
    post 'create_incorrect_task', on: :member
  end

  resources :tasks do
    post 'create_incorrect', on: :member
  end


  resources :courses do
    resources :tasks
  end

  resources :multi_choice_questions do
    post 'submit_answer', on: :member
  end

  resources :multi_choice_answers

  resources :numeric_questions do
    post 'submit_answer', on: :member
    get 'show_hint', on: :member
    get 'show_result', on: :member
  end

  resources :user_progresses

  get '/home', to: 'static_pages#home'

  # Health check route
  get "up" => "rails/health#show", as: :rails_health_check

  # Root path route
  root "static_pages#home"

  post '/tasks/:task_id/submit_answer', to: 'tasks#submit_answer', as: 'submit_answer'
  post 'user_courses/reduce_progress', to: 'user_courses#reduce_progress'
end

staticfy_app/app/models/multi_choice_question.rb
class MultiChoiceQuestion < ApplicationRecord
  belongs_to :task
  has_many :multi_choice_answers, dependent: :destroy
end

staticfy_app/app/controllers/multi_choice_questions_controller.rb
class MultiChoiceQuestionsController < ApplicationController
    before_action :authenticate_user!
    before_action :authenticate_teacher
    before_action :set_multi_choice_question, only: %i[show edit update destroy]

    def index
      @multi_choice_questions = MultiChoiceQuestion.all
    end

    def show
        @multi_choice_question = MultiChoiceQuestion.find(params[:id])
    end

    def new
      @multi_choice_question = MultiChoiceQuestion.new
    end

    def edit
    end

    def create
      choices = {}
      (1..4).each do |i|
        value = params["multi_choice_question"]["choice_#{i}_value"]
        why_not = params["multi_choice_question"]["choice_#{i}_why_not"]
        choices["choice_#{i}"] = { value: value, why_not: why_not }
      end

      @multi_choice_question = MultiChoiceQuestion.new(
        task_id: params[:multi_choice_question][:task_id],
        difficulty: params[:multi_choice_question][:difficulty],
        question: params[:multi_choice_question][:question],
        choice_1: choices["choice_1"].to_json,
        choice_2: choices["choice_2"].to_json,
        choice_3: choices["choice_3"].to_json,
        choice_4: choices["choice_4"].to_json,
        correct_answer: params[:multi_choice_question][:correct_answer]
      )

      if @multi_choice_question.save
          flash[:notice] = 'Pregunta creada correctamente'
      else
          flash[:alert] = 'Ocurrió un error al crear la pregunta'
      end
        redirect_to root_path
    end


    def update
      respond_to do |format|
        if @multi_choice_question.update(multi_choice_question_params)
          format.html { redirect_to @multi_choice_question, notice: 'Pregunta actualizada correctamente' }
          format.json { render :show, status: :ok, location: @multi_choice_question }
        else
          flash.now[:error] = 'Multi choice question update failed'
          format.html { render :edit }
          format.json { render json: @multi_choice_question.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @multi_choice_question.destroy
      respond_to do |format|
        format.html { redirect_to multi_choice_questions_url, notice: 'Pregunta eliminada correctamente.' }
        format.json { head :no_content }
      end
    end

    def submit_answer
        @multi_choice_question = MultiChoiceQuestion.find(params[:id])
        selected_answer = params[:selected_answer]

        # Aquí puedes manejar la lógica de guardar la respuesta, validar si es correcta, etc.
        if selected_answer == @multi_choice_question.correct_answer
          flash[:notice] = 'Correct Answer!'
        else
          flash[:alert] = 'Incorrect Answer.'
        end

        redirect_to @multi_choice_question
    end


    private

      def set_multi_choice_question
        @multi_choice_question = MultiChoiceQuestion.find(params[:id])
      end

      def authenticate_teacher
        unless current_user.role == 'teacher'
          flash[:alert] = 'No tienes permiso para acceder a esta sección.'
          redirect_to root_path
        end
      end

      def multi_choice_question_params
        params.require(:multi_choice_question).permit(:task_id, :difficulty, :question, :choice_1, :choice_2, :choice_3, :choice_4, :correct_answer)
      end
end

staticfy_app/app/views/multi_choice_questions/edit.html.erb
<div class="container mt-4">
  <div class="card shadow">
    <div class="card-header text-center" style="background-color: #28a745; color: white;">
      <h2 class="mb-0">Editar Pregunta de Opción Múltiple</h2>
    </div>
    <div class="card-body">
      <div class="text-center mb-3">
        <svg xmlns="http://www.w3.org/2000/svg" width='50' height='50' viewBox="0 0 24 24" fill="none"><path d="M21.2799 6.40005L11.7399 15.94C10.7899 16.89 7.96987 17.33 7.33987 16.7C6.70987 16.07 7.13987 13.25 8.08987 12.3L17.6399 2.75002C17.8754 2.49308 18.1605 2.28654 18.4781 2.14284C18.7956 1.99914 19.139 1.92124 19.4875 1.9139C19.8359 1.90657 20.1823 1.96991 20.5056 2.10012C20.8289 2.23033 21.1225 2.42473 21.3686 2.67153C21.6147 2.91833 21.8083 3.21243 21.9376 3.53609C22.0669 3.85976 22.1294 4.20626 22.1211 4.55471C22.1128 4.90316 22.0339 5.24635 21.8894 5.5635C21.7448 5.88065 21.5375 6.16524 21.2799 6.40005V6.40005Z" stroke="#28a745" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path><path d="M11 4H6C4.93913 4 3.92178 4.42142 3.17163 5.17157C2.42149 5.92172 2 6.93913 2 8V18C2 19.0609 2.42149 20.0783 3.17163 20.8284C3.92178 21.5786 4.93913 22 6 22H17C19.21 22 20 20.2 20 18V13" stroke="#28a745" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path></svg>      </div>

      <%= form_with(model: @multi_choice_question, local: true, html: { class: 'form' }) do |form| %>
        
        <div class="form-group">
          <%= form.label :question, class: 'form-label text-secondary' %>
          <%= form.text_field :question, class: 'form-control mb-3', placeholder: 'Edita la pregunta aquí' %>
        </div>

        <div class="form-group">
          <%= form.label :choice_1, class: 'form-label text-secondary' %>
          <%= form.text_field :choice_1, class: 'form-control mb-3', placeholder: 'Edita la alternativa 1' %>
        </div>

        <div class="form-group">
          <%= form.label :choice_2, class: 'form-label text-secondary' %>
          <%= form.text_field :choice_2, class: 'form-control mb-3', placeholder: 'Edita la alternativa 2' %>
        </div>

        <div class="form-group">
          <%= form.label :choice_3, class: 'form-label text-secondary' %>
          <%= form.text_field :choice_3, class: 'form-control mb-3', placeholder: 'Edita la alternativa 3' %>
        </div>

        <div class="form-group">
          <%= form.label :choice_4, class: 'form-label text-secondary' %>
          <%= form.text_field :choice_4, class: 'form-control mb-3', placeholder: 'Edita la alternativa 4' %>
        </div>

        <div class="form-group">
          <%= form.label :correct_answer, class: 'form-label text-secondary' %>
          <%= form.text_field :correct_answer, class: 'form-control mb-3', placeholder: 'Edita la respuesta correcta aquí' %>
        </div>

        <div class="form-group">
          <%= form.label :task_id, class: 'form-label text-secondary' %>
          <%= form.collection_select :task_id, Task.where(task_type: 'multi_choice'), :id, :name_with_course, { include_blank: 'Selecciona una tarea' }, { class: 'form-control mb-3' } %>
        </div>

        <div class="form-group">
          <%= form.label :difficulty, class: 'form-label text-secondary' %>
          <%= form.select :difficulty, options_for_select([['Baja', 0], ['Media', 1], ['Alta', 2]], @multi_choice_question.difficulty), { include_blank: 'Selecciona dificultad' }, class: 'form-control mb-3' %>
        </div>

        <div class="form-group text-center">
          <%= form.submit 'Actualizar Pregunta', class: 'btn mt-3', style: 'background-color: #28a745; color: white; border-radius: 0.5rem; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);' %>
          <%= link_to 'Cancelar', multi_choice_questions_path, class: 'btn mt-3', style: 'background-color: #6c757d; color: white; border-radius: 0.5rem; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); margin-left: 10px;' %>
        </div>
      <% end %>
    </div>
  </div>
  </div>
</div>

staticfy_app/app/views/multi_choice_questions/index.html.erb
<div class="container mt-4">
  <div class="card shadow">
    <div class="card-header text-center" style="background-color: #28a745; color: white;">
      <h2 class="mb-0">Preguntas de Opción Múltiple</h2>
    </div>
    <div class="card-body">
      <div class="mb-3 text-center">
        <%= link_to 'Nueva Pregunta', new_multi_choice_question_path, class: 'btn', style: "background-color: #28a745; color: white; border-radius: 0.5rem; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);" %>
      </div>

      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>ID</th>
            <th>Pregunta</th>
            <th>Curso</th>
            <th>Opción 1</th>
            <th>Opción 2</th>
            <th>Opción 3</th>
            <th>Opción 4</th>
            <th>Respuesta Correcta</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @multi_choice_questions.each do |question| %>
            <tr>
              <td><%= question.id %></td>
              <td><%= question.question %></td>
              <td><%= question.task.course.name %></td>
              <td><%= question.choice_1 %></td>
              <td><%= question.choice_2 %></td>
              <td><%= question.choice_3 %></td>
              <td><%= question.choice_4 %></td>
              <td><%= question.correct_answer %></td>
              <td>
                <%= link_to 'Mostrar', multi_choice_question_path(question), class: 'btn mb-2', style: "background-color: #17a2b8; color: white; border-radius: 0.5rem; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);" %>
                <%= link_to 'Editar', edit_multi_choice_question_path(question), class: 'btn mb-2', style: "background-color: #ffc107; color: black; border-radius: 0.5rem; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);" %>
                <%= button_to 'Eliminar', multi_choice_question_path(question), method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn', style: "background-color: #dc3545; color: white; border-radius: 0.5rem; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

staticfy_app/app/views/multi_choice_questions/new.html.erb
<div class="container mt-4">
  <div class="card shadow">
    <div class="card-header text-center" style="background-color: #28a745; color: white;">
      <h2 class="mb-0">Crear Pregunta de Opción Múltiple</h2>
    </div>
    
    <div class="card-body">
      <div class="text-center mb-3">

      <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" viewBox="0 0 24 24" fill="none"><path d="M4 12H20M12 4V20" stroke="#28a745" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path></svg>      </div>

      <%= form_with(model: @multi_choice_question, local: true, html: { class: 'form' }) do |form| %>
        
        <div class="form-group">
          <%= form.label :question, class: 'form-label text-secondary' %>
          <%= form.text_field :question, class: 'form-control mb-3', placeholder: 'Escribe la pregunta aquí' %>
        </div>

        <div class="form-group">
          <%= form.label :choice_1_value, class: 'form-label text-secondary' %>
          <%= form.text_field :choice_1_value, class: 'form-control mb-3', placeholder: 'Escribe la alternativa 1' %>
          <%= form.label :choice_1_why_not, class: 'form-label text-secondary' %>
          <%= form.text_area :choice_1_why_not, class: 'form-control mb-3', placeholder: '¿Por qué no es la respuesta correcta?' %>
        </div>

        <div class="form-group">
          <%= form.label :choice_2_value, class: 'form-label text-secondary' %>
          <%= form.text_field :choice_2_value, class: 'form-control mb-3', placeholder: 'Escribe la alternativa 2' %>
          <%= form.label :choice_2_why_not, class: 'form-label text-secondary' %>
          <%= form.text_area :choice_2_why_not, class: 'form-control mb-3', placeholder: '¿Por qué no es la respuesta correcta?' %>
        </div>

        <div class="form-group">
          <%= form.label :choice_3_value, class: 'form-label text-secondary' %>
          <%= form.text_field :choice_3_value, class: 'form-control mb-3', placeholder: 'Escribe la alternativa 3' %>
          <%= form.label :choice_3_why_not, class: 'form-label text-secondary' %>
          <%= form.text_area :choice_3_why_not, class: 'form-control mb-3', placeholder: '¿Por qué no es la respuesta correcta?' %>
        </div>

        <div class="form-group">
          <%= form.label :choice_4_value, class: 'form-label text-secondary' %>
          <%= form.text_field :choice_4_value, class: 'form-control mb-3', placeholder: 'Escribe la alternativa 4' %>
          <%= form.label :choice_4_why_not, class: 'form-label text-secondary' %>
          <%= form.text_area :choice_4_why_not, class: 'form-control mb-3', placeholder: '¿Por qué no es la respuesta correcta?' %>
        </div>

        <div class="form-group">
          <%= form.label :correct_answer, class: 'form-label text-secondary' %>
          <%= form.text_field :correct_answer, class: 'form-control mb-3', placeholder: 'Escribe la respuesta correcta aquí' %>
        </div>

        <div class="form-group">
          <%= form.label :task_id, class: 'form-label text-secondary' %>
          <%= form.collection_select :task_id, Task.where(task_type: 'multi_choice'), :id, :name_with_course, { include_blank: 'Selecciona una tarea' }, { class: 'form-control mb-3' } %>
        </div>

        <div class="form-group">
          <%= form.label :difficulty, class: 'form-label text-secondary' %>
          <%= form.select :difficulty, options_for_select([['Baja', 0], ['Media', 1], ['Alta', 2]]), { include_blank: 'Selecciona dificultad' }, class: 'form-control mb-3' %>
        </div>

        <div class="form-group text-center">
          <%= form.submit 'Crear Pregunta', class: 'btn mt-3', style: 'background-color: #28a745; color: white; border-radius: 0.5rem; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);' %>
          <%= link_to 'Cancelar', multi_choice_questions_path, class: 'btn mt-3', style: 'background-color: #6c757d; color: white; border-radius: 0.5rem; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); margin-left: 10px;' %>
        </div>
      <% end %>
    </div>
  </div>
  </div>
</div>

staticfy_app/app/views/multi_choice_questions/show.html.erb
<div class="container mt-4" style="max-width: 800px; margin: auto;">
  <div class="card" style="border: none; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);">
    <div class="card-body" style="padding: 2rem;">
      <h5 class="card-title" style="font-weight: bold; color: #28a745;">Detalles de la Pregunta</h5>
      
      <h6 class="card-subtitle mb-2 text-muted">Pregunta</h6>
      <p class="card-text" style="font-size: 1.2rem; margin-bottom: 1.5rem;"><%= @multi_choice_question.question %></p>

      <h6 class="card-subtitle mb-2 text-muted">Alternativas</h6>
      <%= form_with url: submit_answer_multi_choice_question_path(@multi_choice_question), local: true do |form| %>
        <ul class="list-group mb-3">
          <li class="list-group-item" style="padding: 1rem; border-radius: 0.5rem;">
            <%= form.radio_button :selected_answer, @multi_choice_question.choice_1, class: 'form-check-input' %>
            <%= @multi_choice_question.choice_1 %>
          </li>
          <li class="list-group-item" style="padding: 1rem; border-radius: 0.5rem;">
            <%= form.radio_button :selected_answer, @multi_choice_question.choice_2, class: 'form-check-input' %>
            <%= @multi_choice_question.choice_2 %>
          </li>
          <li class="list-group-item" style="padding: 1rem; border-radius: 0.5rem;">
            <%= form.radio_button :selected_answer, @multi_choice_question.choice_3, class: 'form-check-input' %>
            <%= @multi_choice_question.choice_3 %>
          </li>
          <li class="list-group-item" style="padding: 1rem; border-radius: 0.5rem;">
            <%= form.radio_button :selected_answer, @multi_choice_question.choice_4, class: 'form-check-input' %>
            <%= @multi_choice_question.choice_4 %>
          </li>
        </ul>
      <% end %>

      <div class="text-center mt-3">
        <%= link_to raw('<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 512 512" version="1.1" xml:space="preserve" style="width: 35px; height: 35px;"><style type="text/css">.st0{fill:#333333;}</style><g id="Layer_1"></g><g id="Layer_2"><g><path class="st0" d="M217,129.88c-6.25-6.25-16.38-6.25-22.63,0L79.61,244.64c-0.39,0.39-0.76,0.8-1.11,1.23 c-0.11,0.13-0.2,0.27-0.31,0.41c-0.21,0.28-0.42,0.55-0.62,0.84c-0.14,0.21-0.26,0.43-0.39,0.64c-0.14,0.23-0.28,0.46-0.41,0.7 c-0.13,0.24-0.24,0.48-0.35,0.73c-0.11,0.23-0.22,0.45-0.32,0.68c-0.11,0.26-0.19,0.52-0.28,0.78c-0.08,0.23-0.17,0.46-0.24,0.69 c-0.09,0.29-0.15,0.58-0.22,0.86c-0.05,0.22-0.11,0.43-0.16,0.65c-0.08,0.38-0.13,0.76-0.17,1.14c-0.02,0.14-0.04,0.27-0.06,0.41 c-0.11,1.07-0.11,2.15,0,3.22c0.01,0.06,0.02,0.12,0.03,0.18c0.05,0.46,0.12,0.92,0.21,1.37c0.03,0.13,0.07,0.26,0.1,0.39 c0.09,0.38,0.18,0.76,0.29,1.13c0.04,0.13,0.09,0.26,0.14,0.4c0.12,0.36,0.25,0.73,0.4,1.09c0.05,0.11,0.1,0.21,0.15,0.32 c0.17,0.37,0.34,0.74,0.53,1.1c0.04,0.07,0.09,0.14,0.13,0.21c0.21,0.38,0.44,0.76,0.68,1.13c0.02,0.03,0.04,0.06,0.06,0.09 c0.55,0.81,1.18,1.58,1.89,2.29l114.81,114.81c3.12,3.12,7.22,4.69,11.31,4.69s8.19-1.56,11.31-4.69c6.25-6.25,6.25-16.38,0-22.63 l-87.5-87.5h291.62c8.84,0,16-7.16,16-16s-7.16-16-16-16H129.51L217,152.5C223.25,146.26,223.25,136.13,217,129.88z"></path></g></g></svg>'), multi_choice_questions_path, class: 'btn' %>
      </div>
    </div>
  </div>
</div>