staticfy_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    member do
      patch 'promote_to_teacher'
      patch 'promote_to_student'
    end
  end

  resources :multi_choice_questions

  resources :tasks do
    post 'finish', on: :member
    # get 'retry_incorrect', on: :member
    post 'create_incorrect_task', on: :member
  end

  resources :tasks do
    post 'create_incorrect', on: :member
  end


  resources :courses do
    resources :tasks
  end

  resources :multi_choice_questions do
    post 'submit_answer', on: :member
  end

  resources :multi_choice_answers

  resources :numeric_questions do
    post 'submit_answer', on: :member
    get 'show_hint', on: :member
    get 'show_result', on: :member
  end

  resources :user_progresses

  get '/home', to: 'static_pages#home'

  # Health check route
  get "up" => "rails/health#show", as: :rails_health_check

  # Root path route
  root "static_pages#home"

  post '/tasks/:task_id/submit_answer', to: 'tasks#submit_answer', as: 'submit_answer'
  post 'user_courses/reduce_progress', to: 'user_courses#reduce_progress'
end

staticfy_app/app/models/numeric_question.rb
class NumericQuestion < ApplicationRecord
  belongs_to :task
  has_many :numeric_answers
  has_one :numeric_template
end

staticfy_app/app/controllers/numeric_questions_controller.rb
class NumericQuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_teacher, only: %i[index]
  before_action :set_numeric_question, only: %i[show show_hint show_result submit_answer]

  def index
  end

  def show
    @task = @numeric_question.task
    @numeric_template = @numeric_question.numeric_template

    if @numeric_template
      @diagram = @numeric_template.diagram_data

      if @numeric_template.values.present?
        @parsed_values = JSON.parse(@numeric_template.values)
        calculate_correct_answer
        session[:attempts] ||= 0
      else
        flash[:alert] = "No hay Diagramas disponibles"
        redirect_to root_path
      end
    else
      flash[:alert] = "No se encontró una plantilla numérica para esta pregunta."
      redirect_to root_path
    end
  end

  def submit_answer
    @user_answer = params[:user_answer].to_f
    @unit_of_measurement = params[:unit_of_measurement].to_s.upcase
    correct_answer = @numeric_question.correct_answer.to_f
    correct_unit = @numeric_question.unit.to_s.upcase
    user_progress = UserProgress.find_by(user_id: current_user.id)
    user_task = UserTask.find_or_initialize_by(user_id: current_user.id, task_id: @numeric_question.task_id)
    numeric_question_course = @numeric_question.task.course
    user_course = UserCourse.find_or_initialize_by(user_id: current_user.id, course_id: numeric_question_course.id)

    if (@user_answer - correct_answer).abs <= @numeric_question.tolerance && @unit_of_measurement == correct_unit
      session[:is_correct] = true

      # Aqui se marca como finalizada la tarea con la nueva tabla user_task
      user_task.is_finished = true
      user_task.save

      # Sumar puntaje para su avance en el Course y global
      user_course.progress += 3
      user_progress.score += 3

      user_course.progress = [user_course.progress, 10].min

      user_progress.save
      user_course.save

      flash[:notice] = "¡Respuesta correcta! Tu respuesta fue: #{@user_answer}. La respuesta correcta es: #{correct_answer}"
      session[:attempts] = 0
      redirect_to show_result_numeric_question_path(@numeric_question)
    else
      session[:is_correct] = false
      session[:attempts] += 1
      if session[:attempts] <= 3
        flash[:alert] = "Respuesta incorrecta."
        redirect_to show_hint_numeric_question_path(@numeric_question)
      else
        flash[:alert] = "Has agotado los hints!"
        session[:attempts] = 0

        user_course.progress -= 3
        user_progress.score -= 3

        user_course.progress = [user_course.progress, 0].max
        user_progress.score = [user_progress.score, 0].max

        user_progress.save
        user_course.save

        redirect_to show_result_numeric_question_path(@numeric_question)
      end
    end
  end

  def show_hint
    @current_hint = get_hint(session[:attempts])
  end

  def show_result
    @is_correct = session.delete(:is_correct)
  end

  private

  def calculate_correct_answer
    if @diagram == 'template1'
      set_template1_correct_answer
    elsif @diagram == 'template2'
      set_template2_correct_answer
    elsif @diagram == 'template3'
      set_template3_correct_answer
    elsif @diagram == 'template4'
      set_template4_correct_answer
    elsif @diagram == 'template5'
      set_template5_correct_answer
    elsif @diagram == 'template6'
      set_template6_correct_answer
    elsif @diagram == 'template7'
      set_template7_correct_answer
    elsif @diagram == 'template8'
      set_template8_correct_answer
    elsif @diagram == 'template9'
      set_template9_correct_answer
    elsif @diagram == 'template10'
      set_template10_correct_answer
    end
  end

  def set_template1_correct_answer
    @angle_1 = @parsed_values['angle'].sample
    @force_magnitude_1 = @parsed_values['forceMagnitude'].sample
    @question_text_1 = @numeric_question.question.gsub('{A}', @angle_1.to_s).gsub('{B}', @force_magnitude_1.to_s)
    result_1 = @force_magnitude_1 * Math.cos(@angle_1 * Math::PI / 180)
    @answer_template1 = result_1.round(2)

    # Actualizar solo si es el diagrama correcto
    @numeric_question.update(correct_answer: @answer_template1)
  end

  def set_template2_correct_answer
    @angle_2 = @parsed_values['angle'].sample
    @force_magnitude_2 = @parsed_values['forceMagnitude'].sample
    @question_text_2 = @numeric_question.question.gsub('{A}', @angle_2.to_s).gsub('{B}', @force_magnitude_2.to_s)
    result_2 = @force_magnitude_2 * Math.cos(@angle_2 * Math::PI / 180)
    @answer_template2 = result_2.round(2)

    # Actualizar solo si es el diagrama correcto
    @numeric_question.update(correct_answer: @answer_template2)
  end

  def set_template3_correct_answer
    @longitud_3 = @parsed_values['longitud'].sample
    @force_magnitude_3 = @parsed_values['forceMagnitude'].sample
    @question_text_3 = @numeric_question.question.gsub('{A}', @force_magnitude_3.to_s).gsub('{B}', @longitud_3.to_s)
    result_3 = @force_magnitude_3 * @longitud_3
    @answer_template3 = result_3.round(2)

    # Actualizar solo si es el diagrama correcto
    @numeric_question.update(correct_answer: @answer_template3)
  end

  def set_template4_correct_answer
    @longitud_4 = @parsed_values['longitud'].sample
    @force_magnitude_4 = @parsed_values['forceMagnitude'].sample
    @question_text_4 = @numeric_question.question.gsub('{A}', @longitud_4.to_s).gsub('{B}', @force_magnitude_4.to_s)

    result_4 = 0.5 * @longitud_4 * @force_magnitude_4
    @answer_template4 = result_4.round(2)

    # Actualizar solo si es el diagrama correcto
    @numeric_question.update(correct_answer: @answer_template4)
  end

  def set_template5_correct_answer
    @masa_5 = @parsed_values['masa'].sample
    @angle_5 = @parsed_values['angle'].sample
    @roce_5 = @parsed_values['roce'].sample
    @question_text_5 = @numeric_question.question.gsub('{A}', @masa_5.to_s).gsub('{B}', @angle_5.to_s).gsub('{C}', @roce_5.to_s)
    fN = @masa_5 * 9.8 * Math.cos(@angle_5 * Math::PI / 180)
    fr = @roce_5 * fN
    fwx = @masa_5 * 9.8 * Math.sin(@angle_5 * Math::PI / 180)

    result_5 = fr + fwx
    @answer_template5 = result_5.round(2)

    # Actualizar solo si es el diagrama correcto
    @numeric_question.update(correct_answer: @answer_template5)
  end

  def set_template6_correct_answer
    @masa_6 = @parsed_values['masa'].sample
    @roce_6 = @parsed_values['roce'].sample
    @roce_polea_6 = @parsed_values['roce_polea'].sample
    @question_text_6 = @numeric_question.question.gsub('{A}', @masa_6.to_s).gsub('{B}', @roce_6.to_s).gsub('{C}', @roce_polea_6.to_s)
    result_6 = @roce_6 * @masa_6 * 9.8 * Math::E**(@roce_polea_6 * Math::PI / 2)
    @answer_template6 = result_6.round(2)

    # Actualizar solo si es el diagrama correcto
    @numeric_question.update(correct_answer: @answer_template6)
  end

  def set_template7_correct_answer
    @forcePosition_7 = @parsed_values['forcePosition'].sample
    @force_magnitude_7 = @parsed_values['forceMagnitude'].sample
    @length_7 = 10.0 
    
    rb = (@force_magnitude_7 * @forcePosition_7) / @length_7
    ra = @force_magnitude_7 - rb
    
    result_7 = ra 
  
    @question_text_7 = @numeric_question.question.gsub('{A}', @forcePosition_7.to_s).gsub('{B}', @force_magnitude_7.to_s)
    @answer_template7 = result_7.round(2)

    # Actualizar solo si es el diagrama correcto
    @numeric_question.update(correct_answer: @answer_template7)
  end

  def set_template8_correct_answer
    @longitud_8 = @parsed_values['longitud'].sample
    @force_magnitude_8 = @parsed_values['forceMagnitude'].sample
    @question_text_8 = @numeric_question.question.gsub('{A}', @force_magnitude_8.to_s).gsub('{B}', @longitud_8.to_s)
    @length_8 = 6 

    rb = (@force_magnitude_8 * @longitud_8) /  @length_8
    rc = rb

    result_8 = rc
    @answer_template8 = result_8.round(2)

    # Actualizar solo si es el diagrama correcto
    @numeric_question.update(correct_answer: @answer_template8)
  end

  def set_template9_correct_answer
    @masa_9 = @parsed_values['masa'].sample
    @question_text_9 = @numeric_question.question.gsub('{A}', @masa_9.to_s)
    result_9 = @masa_9 * 9.8
    @answer_template9 = result_9.round(2)

    # Actualizar solo si es el diagrama correcto
    @numeric_question.update(correct_answer: @answer_template9)
  end

  def set_template10_correct_answer
    @masa_10 = @parsed_values['masa'].sample
    @angle_10 = @parsed_values['angle'].sample
    @question_text_10 = @numeric_question.question.gsub('{A}', @masa_10.to_s).gsub('{B}', @angle_10.to_s)
    fp = @masa_10 * 9.8
    result_10 = fp * Math.cos(@angle_10 * Math::PI / 180)
    @answer_template10 = result_10.round(2)

    # Actualizar solo si es el diagrama correcto
    @numeric_question.update(correct_answer: @answer_template10)
  end

  def get_hint(counter)
    case counter
    when 1
      @numeric_question.hint_1
    when 2
      @numeric_question.hint_2
    when 3
      @numeric_question.hint_3
    else
      "No hay más hints"
    end
  end

  def set_numeric_question
    @numeric_question = NumericQuestion.find(params[:id])
  end

  def numeric_question_params
    params.require(:numeric_question).permit(:task_id, :difficulty, :question, :correct_answer, :tolerance, :unit, :hint_1, :hint_2, :hint_3)
  end

  def authenticate_teacher
    unless current_user.role == 'teacher'
      flash[:alert] = 'No tienes permiso para acceder a esta sección.'
      redirect_to root_path
    end
  end
end

staticfy_app/app/views/numeric_questions/show.html.erb
<div class="container mt-4" style="max-width: 800px; margin: auto;">
  <div class="card" style="border: none; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);">
    <div class="card-body" style="padding: 2rem;">
      <div id="question-container">

        <% if @diagram == 'template1' %>
        <h5 class="mb-3" style="font-weight: 700;"><%= @question_text_1 %></h5>
            <p>Considere la respuesta en N (<%= @numeric_question.correct_answer %>)</p>
         <div class="container text-center mt-3 mb-5">
          <%= render 'templates/template1' %>
        </div>
        <% elsif @diagram == 'template2' %>
        <h5 class="mb-3" style="font-weight: 700;"><%= @question_text_2 %></h5>
          <p>Considere la respuesta en N (<%= @numeric_question.correct_answer %>)</p>
          <div class="container text-center mt-3 mb-5">
            <%= render 'templates/template2' %>
          </div>
        <% elsif @diagram == 'template3' %>
        <h5 class="mb-3" style="font-weight: 700;"><%= @question_text_3 %></h5>
          <p>Considere la respuesta en N (<%= @numeric_question.correct_answer %>)</p>
          <div class="container text-center mt-3 mb-5">
            <%= render 'templates/template3' %>
          </div>
        <% elsif @diagram == 'template4' %>
        <h5 class="mb-3" style="font-weight: 700;"><%= @question_text_4 %></h5>
          <p>Considere la respuesta en N (<%= @numeric_question.correct_answer %>)</p>
          <div class="container text-center mt-3 mb-5">
            <%= render 'templates/template4' %>
          </div>
        <% elsif @diagram == 'template5' %>
        <h5 class="mb-3" style="font-weight: 700;"><%= @question_text_5 %></h5>
          <p>Considere la respuesta en N (<%= @numeric_question.correct_answer %>)</p>
          <div class="container text-center mt-3 mb-5">
            <%= render 'templates/template5' %>
          </div>
        <% elsif @diagram == 'template6' %>
        <h5 class="mb-3" style="font-weight: 700;"><%= @question_text_6 %></h5>
          <p>Considere la respuesta en N (<%= @numeric_question.correct_answer %>)</p>
          <div class="container text-center mt-3 mb-5">
            <%= render 'templates/template6' %>
          </div>
        <% elsif @diagram == 'template7' %>
        <h5 class="mb-3" style="font-weight: 700;"><%= @question_text_7 %></h5>
          <p>Considere la respuesta en N (<%= @numeric_question.correct_answer %>)</p>
          <div class="container text-center mt-3 mb-5">
            <%= render 'templates/template7' %>
          </div>
        <% elsif @diagram == 'template8' %>
        <h5 class="mb-3" style="font-weight: 700;"><%= @question_text_8 %></h5>
          <p>Considere la respuesta en N (<%= @numeric_question.correct_answer %>)</p>
          <div class="container text-center mt-3 mb-5">
            <%= render 'templates/template8' %>
          </div>
        <% elsif @diagram == 'template9' %>
        <h5 class="mb-3" style="font-weight: 700;"><%= @question_text_9 %></h5>
          <p>Considere la respuesta en N (<%= @numeric_question.correct_answer %>)</p>
          <div class="container text-center mt-3 mb-5">
            <%= render 'templates/template9' %>
          </div>
        <% elsif @diagram == 'template10' %>
        <h5 class="mb-3" style="font-weight: 700;"><%= @question_text_10 %></h5>
          <p>Considere la respuesta en N (<%= @numeric_question.correct_answer %>)</p>
          <div class="container text-center mt-3 mb-5">
            <%= render 'templates/template10' %>
          </div>
        <% end %>
        
        <div class="d-flex justify-content-center align-items-center mb-5">
          <%= form_with url: submit_answer_numeric_question_path(@numeric_question), method: :post do %>
            <div class="d-flex align-items-center">
              <div class="form-group mb-0">
                <%= text_field_tag :user_answer, nil, class: 'form-control', placeholder: 'Ingresa tu respuesta:', style: 'border: 1px solid black; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3)' %>
              </div>
              <div class="form-group mb-0 ms-2">
                <%= text_field_tag :unit_of_measurement, nil, class: 'form-control', placeholder: 'Unidad de medida:', style: 'border: 1px solid black; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3)' %>
              </div>
              <button type="submit" class="btn" style="border: 1px solid black; background: none; cursor: pointer; margin-left: 10px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3)">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" width="24" height="24">
                  <path d="M10 14L12.2728 19.3032C12.5856 20.0331 13.5586 20.1103 13.9486 19.4185C14.7183 18.0535 15.8591 15.8522 17 13C19 8 20 4 20 4C20 4 16 5 11 7C8.14784 8.14086 5.94647 9.28173 4.58149 10.0514C3.88975 10.4414 3.96687 11.4144 4.69678 11.7272L10 14Z" stroke="#000000" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                </svg>
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

staticfy_app/app/views/numeric_questions/show_hint.html.erb
<div class="container mt-4" style="max-width: 800px; margin: auto;">
    <div class="card" style="border: none; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);">
        <div class="card-body" style="padding: 2rem;">
          <!-- <svg xmlns="http://www.w3.org/2000/svg" fill="rgba(0, 77, 0, 1)" viewBox="0 0 200 200" data-name="Layer 1" id="Layer_1" width="50" height="50">
            <path d="M114,100l49-49a9.9,9.9,0,0,0-14-14L100,86,51,37A9.9,9.9,0,0,0,37,51l49,49L37,149a9.9,9.9,0,0,0,14,14l49-49,49,49a9.9,9.9,0,0,0,14-14Z"></path>
          </svg>           -->
          <h1 class="hero-title-tasks">¡Oh no! 😅 La respuesta fue incorrecta.</h1>
          <h5 class="mb-3" style="font-weight: 700;"> ¡No te preocupes, aquí va una pista para ayudarte! 💡: </h5>
          <h5 class="d-flex justify-content-center mt-4" style="font-weight: 700; font-style: italic;"> <%= @current_hint %></h5>

            <div class="d-flex justify-content-center mt-4">
              <%= button_to "Volver a la Pregunta", numeric_question_path(@numeric_question), method: :get, id: "retry_button", class: "btn btn-primary me-2" %>
              <%= button_to "Saltar Tarea", courses_path, method: :get, class: "btn btn-danger" %>
            </div>            
        </div>
    </div>
</div>


<script>
  document.getElementById('retry_button').onclick = function() {
    setTimeout(function() {
      window.location.reload();
    }, 1000);
  };
</script>

staticfy_app/app/views/numeric_questions/show_result.html.erb
<% if @is_correct %>
  <div class="container mt-4" style="max-width: 800px; margin: auto;">
    <div class="card" style="border: none; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);">
      <div class="card-body" style="padding: 2rem;">
        <h1 class="hero-title-tasks">¡Felicidades!</h1>
        <h5 class="mb-3" style="font-weight: 700;">¡Correcto! 🎉 La respuesta es: <%= @numeric_question.correct_answer %> N. ¡Buen trabajo! 🚀</h5>
        <div class="d-flex justify-content-center mt-4">
          <%= button_to "Volver al Modulo", courses_path, method: :get, class: "btn btn-primary me-2" %>
        </div> 
      </div>
    </div>
  </div>
<% else %>
  <div class="container mt-4" style="max-width: 800px; margin: auto;">
    <div class="card" style="border: none; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);">
      <div class="card-body" style="padding: 2rem;">
        <h1 class="hero-title-tasks">¡Oh no! 😅 La respuesta fue incorrecta.</h1>
        <h5 class="mb-3" style="font-weight: 700;"> ¡Te quedaste sin mas hints! 🎯 ¡No te desanimes, sigue intentándolo! 💪</h5>  
        <h6 class="d-flex justify-content-center mt-4" style="font-weight: 700; font-style: italic;"> <%= @numeric_question.hint_1 %></h6>
        <h6 class="d-flex justify-content-center mt-4" style="font-weight: 700; font-style: italic;"> <%= @numeric_question.hint_2 %></h6>
        <h6 class="d-flex justify-content-center mt-4" style="font-weight: 700; font-style: italic;"> <%= @numeric_question.hint_3 %></h6>

        <div class="d-flex justify-content-center mt-4">
          <%= button_to "Volver a la Pregunta", numeric_question_path(@numeric_question), method: :get, id: "retry_button", class: "btn btn-primary me-2" %>
          <%= button_to "Saltar Tarea", courses_path, method: :get, class: "btn btn-danger" %>
        </div>    
      </div>
    </div>
  </div>
<% end %>


<script>
  document.getElementById('retry_button').onclick = function() {
    setTimeout(function() {
      window.location.reload();
    }, 1000);
  };
</script>